_commit: v1.6.18-4-gf354859
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: loki
helmRelease: loki
helmRepo: https://grafana.github.io/helm-charts
helmValues: helm/values.yaml
helmVersion: ''
ingress: false
labels: ''
name: loki
namespace: loki
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://grafana.com/docs/loki/latest/
url: https://github.com/charlesthomas/homelab-loki
