_commit: v1.9.0-1-g02b6330
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: loki
helmRelease: loki
helmRepo: https://grafana.github.io/helm-charts
helmValues: helm/values.yaml
helmVersion: 6.5.2
homepageEnabled: false
ingress: false
labels: ''
name: loki
namespace: loki
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://grafana.com/docs/loki/latest/
url: https://github.com/charlesthomas/homelab-loki
