_commit: v1.8.1
_src_path: /home/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: true
helmCrds: false
helmName: loki
helmRelease: loki
helmRepo: https://grafana.github.io/helm-charts
helmValues: helm/values.yaml
helmVersion: ''
homepageEnabled: true
ingHost: loki.crt.house
ingName: loki
ingress: false
labels: ''
name: loki
namespace: loki
pvc: false
reloader: false
resources: []
service: false
serviceAccount: false
upstreamURL: https://grafana.com/docs/loki/latest/
url: https://github.com/charlesthomas/homelab-loki
