---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-loki

resources:
- resources/namespaces.yaml
helmCharts:
- name: loki
  namespace: loki
  releaseName: loki
  repo: https://grafana.github.io/helm-charts
  valuesFile: helm/values.yaml
  version: 6.5.2
