---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-loki

resources:
- resources/namespaces.yaml
patches:
- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: loki
      namespace: loki
      annotations:
        gethomepage.dev/href: https://loki.crt.house
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: 
        gethomepage.dev/group: 
        gethomepage.dev/icon: loki
        gethomepage.dev/name: loki
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
helmCharts:
- name: loki
  namespace: loki
  releaseName: loki
  repo: https://grafana.github.io/helm-charts
  valuesFile: helm/values.yaml
